# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Android World
tagline:             'By 英斌'
description:         '微店Android高级开发工程师，欢迎技术非技术交流.'
url:                 http://killermyth.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              吕英斌
  url:               https://twitter.com/mdo
  email:             killermyth@gmail.com

# Custom vars
version:             1.0.0
